[WiP] Refactored BMS driver for boolean support
4am-robotics/cob_driver pull request #303
Opened 2017-01-11 23:27 UTC by ipa-mdl

fixes #302 

Needs to be tested on hardware.

2017-01-13 17:12 UTC, ipa-mdl commented
fixed some bugs during hardware testing

2017-01-13 17:55 UTC, benmaidel approved these changes

2017-01-17 16:16 UTC, floweisshardt requested changes

2017-01-17 16:16 UTC, ipa-fmw commented on cob_bms_driver/include/cob_bms_driver/cob_bms_driver_node.h
> +            void produceDiagnostics(diagnostic_updater::DiagnosticStatusWrapper &stat);
tabs vs spaces

2017-01-17 16:19 UTC, ipa-mdl commented on cob_bms_driver/include/cob_bms_driver/cob_bms_driver_node.h
> +            void produceDiagnostics(diagnostic_updater::DiagnosticStatusWrapper &stat);
not tabs, just indention is wrong.
I am not sure when I can fix the white space issues.

2017-01-19 08:29 UTC, NadiaHG approved these changes
Test on cob4-7: OK

2017-01-19 08:29 UTC, floweisshardt approved these changes

2017-01-19 08:29 UTC, merged