[HOTFIX] fix powerstate aggregator charging flag
4am-robotics/cob_driver pull request #307
Opened 2017-02-02 16:36 UTC by ipa-fmw

bms is not delivering correct flag for full battery and docked

2017-02-02 16:44 UTC, fmessmer reviewed
Review

2017-02-02 16:44 UTC, ipa-fxm commented on cob_bms_driver/src/power_state_aggregator.py
> -        self.charging = msg.data
So, if this is a temporary workaround and the flag will later be retrieved from bms again, don't you want to keep the subscriber - simply comment `self.charging = msg.data`?

2017-02-02 16:44 UTC, ipa-fxm commented on cob_bms_driver/src/power_state_aggregator.py
> +        if msg.data > -1: # we use a limit of -1Ampere because if the battery is 100% fuland the robot is still docked, there is no more current going into the battery. -1 A is biggger than the "Ruhe
....`fuland` :arrow_forward: `full and`....

2017-02-03 09:23 UTC, ipa-fxm commented
@ipa-fmw 
Even better, could we not apply this workaround in bms driver itself? I.e. set the `charging` flag using the metric you propose, i.e. `current < -1 A`? That way we would not need to "remember" adjusting the power_state_aggregator after fixing bms...!

2017-02-03 09:23 UTC, fmessmer requested changes
@ipa-fmw 
Even better, could we not apply this workaround in bms driver itself? I.e. set the `charging` flag using the metric you propose, i.e. `current < -1 A`? That way we would not need to "remember" adjusting the power_state_aggregator after fixing bms...!

2017-02-07 16:20 UTC, ipa-bnm commented
Isn't there any way to detect if the robot is connected to the docking station? This way we could introduce a new flag `docked` and leave the charging flag as it is!

2017-02-07 21:59 UTC, ipa-fmw commented on cob_bms_driver/src/power_state_aggregator.py
> +        if msg.data > -1: # we use a limit of -1Ampere because if the battery is 100% fuland the robot is still docked, there is no more current going into the battery. -1 A is biggger than the "Ruhe
done

2017-02-07 22:05 UTC, ipa-fmw commented
@ipa-fxm: we cannot fix this in the bms driver because the driver only publishes raw data. the power_state_aggregator is the node which accumulated the various topics from the bms driver into a consistent power_state

@ipa-bnm: no there is no direct way to detect the `docked` status. What we can do is to keep charging as it is (current switch = 0) and introduce a new field docked in power_state (current switch = -1). But changing the PowerState message this will lead to inconsistent and not analysable bag files from Oct to now. So I prefer to keep the workaround and fix it properly as soon as the bms is capable of detecting this (probably takes until summer 20XX)

2017-02-09 07:29 UTC, ipa-fmw commented
I'd like to merge this as we're finalising testing on cob4-2 and I'd like to ship an up-to-date but well tested installation.

2017-02-09 07:29 UTC, merged

2017-02-09 08:06 UTC, ipa-fxm commented
workaround for #308