renamed max_voltage to more descriptive voltage_divider_factor
4am-robotics/cob_driver pull request #330
Opened 2017-03-28 09:07 UTC by ipa-jba

depends on https://github.com/ipa320/cob_robots/pull/623
sorry about changes in whitespace

2017-03-28 13:10 UTC, floweisshardt requested changes

2017-03-28 13:10 UTC, ipa-fmw commented on cob_phidget_power_state/scripts/power_state_phidget.py
> +        self.voltage_divider_factor = rospy.get_param("~voltage_divider_factor", 59.5)
if this is no more a maximum voltage is there a better default value? If not, I would make this a non-optional parameter and thow an error if missing.

2017-03-28 13:53 UTC, floweisshardt approved these changes

2017-03-28 21:20 UTC, ipa-fxm commented
imho, the descriptiveness of `voltage_divider_factor` isn't much better...but I leave this to you guys...

2017-03-29 07:31 UTC, ipa-jba commented
I see your point. what about `voltage_divider_ratio` and changing the values and computation to `1/voltage_divider_factor` to keep it consistent with the general case described by wikipedia: https://en.wikipedia.org/wiki/Voltage_divider
?

2017-03-29 07:39 UTC, ipa-fxm commented
No need to make it more complicated than it is....if everybody is ok, go for it...(add a descriptive comment, if you like)...

2017-03-29 07:51 UTC, ipa-jba commented
@ipa-bnm you implemented the node. whats your opinion?

2017-04-05 10:29 UTC, fmessmer approved these changes

2017-04-05 10:29 UTC, merged

2017-04-07 14:16 UTC, ipa-bnm commented
@ipa-jba too late ;)