Fix/uninterrupted emotion switch
4am-robotics/cob_driver pull request #339
Opened 2017-06-26 12:51 UTC by ipa-fmw

includes https://github.com/ipa320/cob_driver/pull/337
additional cleanup and mutex threaded calls

2017-06-26 13:17 UTC, ipa-fmw commented
depends on https://github.com/ros/rosdistro/pull/15366

2017-06-27 14:05 UTC, ipa-fmw commented
ros/rosdistro#15366 is merged, so we're OK to merge this one too.

2017-07-03 16:35 UTC, fmessmer requested changes
not tested yet, just visual review:
 - remove the __init__.py file
 - please fix the license (it says cob_gazebo_objects!!!)

2017-07-07 17:43 UTC, fmessmer approved these changes

2017-07-10 08:04 UTC, merged