set relative remaining capacity
4am-robotics/cob_driver pull request #361
Opened 2017-11-28 12:58 UTC by ipa-fxm

I found setting the `relative_remaining_capacity` more intuitive than setting the `remaining_capacity` when testing low-battery behavior in msh
This is due to all battery-monitor conditions take `relative_remaining_capacity` into account, but `relative_remaining_capacity` is computed only in the [`power_state_aggregator`](https://github.com/ipa320/cob_driver/blob/indigo_dev/cob_bms_driver/src/power_state_aggregator.py#L81)

2017-11-28 14:23 UTC, ipa-rmb submitted a review, later dismissed

2017-11-30 07:22 UTC, ipa-fxm commented
@ipa-rmb @ipa-jba @ipa-fez @ipa-bnm @ipa-fmw 
I'd need another review here

2017-11-30 08:05 UTC, ipa-fez requested changes

2017-11-30 08:05 UTC, ipa-fez commented on cob_bms_driver/src/fake_bms.py
> +        self.remaining_capacity += round(((self.current/self.poll_frequency)/3600), 5)
Won't this prevent the capacity from updating if the delta is very small and always rounded to 0? Is there a reason you need to round?

2017-11-30 09:22 UTC, ipa-fxm commented
thx for the comments...please approve again :wink:

2017-11-30 11:46 UTC, floweisshardt approved these changes

2017-11-30 11:47 UTC, merged