replace boost::shared_ptr
4am-robotics/cob_driver pull request #380
Opened 2018-08-06 13:42 UTC by ipa-jba

with std::shared_ptr

(deprecation.. for melodic)

2018-08-06 20:56 UTC, fmessmer requested changes
apparently not "multi-distro-compatible"
do we need to introduce a `melodic-devel` branch`? or can it be made compatible?

also, please add melodic checks for travis here, too

2019-04-10 10:11 UTC, ipa-jba commented
Unfortunately we will need a melodic-devel branch. 
Some drivers use socketcan_interface where the pointers were renamed for example from `Interface::Ptr` to `InterfaceSharedPtr` and "retyped" from boost do std. I think it would be unreasonable effort to keep compatibility for kinetic(and earlier) and make it work for melodic

2019-04-10 21:47 UTC, ipa-mdl commented
> Some drivers use socketcan_interface where the pointers were renamed

Actually, it should be API-compatible between kinetic and melodic.

2019-04-11 15:02 UTC, ipa-jba commented
> Actually, it should be API-compatible between kinetic and melodic.

Indeed. cob_drivers supports indigo and kinetic. in Listener for example the Listener::Ptr was marked deprecated but still used here https://github.com/ipa320/cob_driver/pull/380/files#diff-92aa77383a887ecfd66e061c1ef3e5e3R75

now with melodic the ::Ptr was removed and the introduced (since kinetic) …ConstSharedPtr is the only available option.

--> this is not an issue of API-compatibility between kinetic and melodic (which is indeed true) but the api compatibility between indigo and melodic.

Introducing a new kinetic branch while tackling issues produced by melodic seems counterintuitive to me even though we likely can support melodic and kinetic just by dropping indigo.

2019-04-11 19:08 UTC, ipa-mdl commented
Indigo is almost EOL (~ 2 weeks left), but kinetic will be supported for the next two years..

2019-04-11 19:41 UTC, fmessmer commented
while introducing a `kinetic_dev` branch to deal with kinetic/melodic compatibility results in some *.rosintall file trouble, it seems the correct way to do...
`indigo_dev` could still be used for kinetic - although it might not include the latest kinetic updates...
for the new branch `kinetic_dev` we should also bump the version to `0.7.X`

2019-04-11 19:45 UTC, fmessmer commented on .travis.yml
> +    - ROS_DISTRO=melodic UPSTREAM_WORKSPACE=debian
if we merge this into a `kinetic_dev` branch (kinetic/melodic) we should include the kinetic jobs again and provide respective rosinstall file (if needed)

2019-04-11 19:47 UTC, fmessmer commented
on a `kinetic_dev` branch, we could even consider removing packages which we do not need anymore and we do not want to migrate to melodic

2019-04-11 19:48 UTC, fmessmer commented
on a side note:
something similar might need to be done for downstream repos...e.g. cob_robots is using `indigo_dev` branch which in fact has not been indigo-compatible for quite some time now...

2019-04-11 21:36 UTC, ipa-mdl commented on cob_elmo_homing/src/plugin.cpp
> +    ElmoMotor402(const std::string &name, std::shared_ptr<canopen::ObjectStorage> storage, const canopen::Settings &settings)
Use the pointer names here as well. Otherwise is does not work on kinetic.

2019-05-03 07:29 UTC, ipa-jba commented
The recent changes were 
a) fix the commented part by ipa-mdl
b) rebase on ipa320/indigo_dev
c) merge/cherry-pick #391

2019-05-03 07:33 UTC, fmessmer commented
So, this is going to be the PR where we collect everything needed to make `cob_driver` `kinetic`- and `melodic`-compatible?
I'd :+1: this

Then, once this PR passes Travis, we would create a new branch `kinetic_dev` and retarget the PR?

2019-05-03 08:08 UTC, ipa-jba commented
travis failed with rosdep issues and I found no option to restart --> close and open this PR

2019-05-03 08:30 UTC, ipa-mdl commented
#391 does not work with kinetic. (at least out-of-the-box)

2019-05-03 08:35 UTC, ipa-mdl commented on cob_elmo_homing/CMakeLists.txt
> +add_compile_options(-std=c++11)
Wrong file?

2019-05-03 09:43 UTC, ipa-mdl commented on cob_elmo_homing/src/plugin.cpp
> +        canopen::MotorBaseSharedPtr mbsp;
please use the `ROSCANOPEN_MAKE_SHARED` macro

2019-05-03 09:44 UTC, ipa-mdl commented on cob_elmo_homing/CMakeLists.txt
> +add_compile_options(-std=c++11)
And remove it here, I cannot guarantee that it works properly with C++1 mixed in for kinetic

2019-08-01 13:03 UTC, fmessmer commented
I changed the target branch for this PR to **new branch** `kinetic_dev` - as it is no longer indigo compatible

2019-08-06 14:09 UTC, fmessmer approved these changes

2019-08-06 14:10 UTC, merged