Feature/reduce load
4am-robotics/cob_driver pull request #397
Opened 2019-07-18 10:43 UTC by LoyVanBeek

- fixes https://github.com/mojin-robotics/cob4/issues/1193

Decoding highly compressed .mp4 files requires a lot of CPU. This PR introduces a parameter that will decompress the files either at init or during a mimic. 
The latter option will make that a *next* use of that mimic is faster.

2019-07-23 11:16 UTC, floweisshardt commented
not needed anymore for mimic videos due to https://github.com/ipa320/cob_driver/pull/398.

do we still want to merge this then?

2019-07-23 11:23 UTC, HannesBachter commented
if the first start of a mimic is still as fast as it was before (and subsequent loadings are quicker), I would merge (as we're only improving)

2019-07-23 11:44 UTC, LoyVanBeek commented
I wouldn't merge it. Compressing files is not the responsibility of `cob_mimic`, it feels like a bit of a hack and it kind of is... The alternative is much cleaner and simpler in that regard

2019-07-29 17:51 UTC, fmessmer requested changes
yes, I wouldn't merge as well..but we could keep it open in case it pops up in the future...

2024-01-04 12:43 UTC, closed without merging