Publish unified points
4am-robotics/cob_driver pull request #424
Opened 2021-07-06 10:28 UTC by lpk1950

- added a publisher for unified pointcloud
 - added a param 'point_cloud' for requesting to publish the unified scan as unified pointcloud

2021-07-06 12:26 UTC, jabbenseth requested changes

2021-07-06 12:26 UTC, jabbenseth commented on cob_scan_unifier/src/scan_unifier_node.cpp
> +  topicPub_PointcloudUnified_ = nh_.advertise<sensor_msgs::PointCloud2>("/pointcloud_unified", 1);
use the same namespace as for scan_unified
```suggestion
  topicPub_PointcloudUnified_ = nh_.advertise<sensor_msgs::PointCloud2>("pointcloud_unified", 1);
```

2021-07-06 12:26 UTC, jabbenseth commented on cob_scan_unifier/src/scan_unifier_node.cpp
> +    if(!pnh_.hasParam("point_cloud"))
maybe for better semantic naming call your parameter `publish_point_cloud` or something alike

also why is the parameter checked in the 
```
if (pnh_.getParam("input_scans", topicList))
{
```
section and not in the "root" of `getParams()`

2021-07-06 12:26 UTC, jabbenseth commented on cob_scan_unifier/src/scan_unifier_node.cpp
> +  projector_.transformLaserScanToPointCloud(frame_, unified_scan, unified_point, listener_);
this is only needed if config_.pub_point_cloud is true?

2021-07-06 12:26 UTC, jabbenseth commented on cob_scan_unifier/src/scan_unifier_node.cpp
> +  }
there is a lot of duplicated code here. is it possible to move that to "unifyLaserScans" or create a "publish" that handles publishing scan and point cloud

2021-07-07 06:18 UTC, fmessmer requested changes
in addition to @jabbenseth review

2021-07-07 06:18 UTC, fmessmer commented on cob_scan_unifier/include/cob_scan_unifier/scan_unifier_node.h
> +      bool pub_point_cloud;
as suggested by @jabbenseth - rename to `publish_pointcloud`

2021-07-07 06:18 UTC, fmessmer commented on cob_scan_unifier/src/scan_unifier_node.cpp
> +  bool point_cloud;
get rid of this local helper variable
you can directly write `config_.publish_pointcloud` in both if and else case respectively

2021-07-07 06:18 UTC, fmessmer commented on cob_scan_unifier/src/scan_unifier_node.cpp
> +    pnh_.getParam("point_cloud", point_cloud);
indentation is wrong

2021-07-07 06:18 UTC, fmessmer commented on cob_scan_unifier/src/scan_unifier_node.cpp
> +  topicPub_PointcloudUnified_.publish(unified_point);
indentation is wrong

2021-07-07 06:18 UTC, fmessmer commented on cob_scan_unifier/src/scan_unifier_node.cpp
> +  topicPub_PointcloudUnified_.publish(unified_point);
indentation is wrong

2021-07-07 06:18 UTC, fmessmer commented on cob_scan_unifier/src/scan_unifier_node.cpp
> +  topicPub_PointcloudUnified_.publish(unified_point);
indentation is wrong

2021-07-07 12:10 UTC, jabbenseth requested changes

2021-07-07 12:10 UTC, jabbenseth commented on cob_scan_unifier/include/cob_scan_unifier/scan_unifier_node.h
> +    void Publish(sensor_msgs::LaserScan& unified_scan);
methods should be lower case 
(publish)

2021-07-07 13:29 UTC, jabbenseth approved these changes, later dismissed

2021-08-05 12:00 UTC, fmessmer approved these changes

2021-08-05 12:03 UTC, merged