[AUDI] adjust battery capacity and discharging values to new diff base
4am-robotics/cob_driver pull request #436
Opened 2022-08-09 12:21 UTC by HannesBachter

2022-08-09 14:59 UTC, floweisshardt requested changes
Do not merge. This will break with cob4 base compatibility. 

Maybe those changes are not needed at all. See https://github.com/mojin-robotics/cob4/issues/2526#issuecomment-1209493456

2022-08-09 17:41 UTC, fmessmer requested changes

2022-08-09 17:41 UTC, fmessmer commented on cob_bms_driver/src/fake_bms.py
> +        self._temperature          = 25.0 # °C
I would make those configurable via a new `battery.yaml` in `mojin_hardware_config`, i.e. `rospy.get_param('voltage', 48)` defaulting to the old/cob4 values...i.e. open a PR that adds these `battery.yaml` file in `mojin_robots` and add a `rosparam` line in the respective `mojin_bringup` launch files

2022-08-09 17:42 UTC, fmessmer commented on cob_bms_driver/src/fake_bms.py
> +        self._temperature          = 25.0 # °C
make sure the `battery.yaml` includes also the values for https://github.com/ipa320/cob_docking/pull/84#discussion_r941630133

2022-08-16 07:00 UTC, fmessmer approved these changes

2022-08-16 07:00 UTC, fmessmer commented on cob_bms_driver/src/fake_bms.py
> +        self._temperature          = 25.0 # °C
done in https://github.com/mojin-robotics/mojin_robots/pull/515

2022-08-16 07:51 UTC, merged